test success

diff --git a/.github/workflows/test-3jobs.yml b/.github/workflows/test-3jobs.yml
--- a/.github/workflows/test-3jobs.yml
+++ b/.github/workflows/test-3jobs.yml
@@ -25,8 +25,9 @@ jobs:
     steps: 
       - name: running job2
         run: echo "Running JOb 2"
-      - name: Try to fail
-        run: exit 1
+      #- name: Try to fail
+      #  run: exit 1
+
   job3:
     runs-on: ubuntu-latest
     needs: [job1,job2]
